// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwUFqMcLgGwtvy4hUs2fgjP2Zbb3RtkBk',
    appId: '1:952082308730:web:fb104901722a4f741d25c3',
    messagingSenderId: '952082308730',
    projectId: 'auth-app-savage',
    authDomain: 'auth-app-savage.firebaseapp.com',
    storageBucket: 'auth-app-savage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7qbcEKbmnWNFwCykW9YnwEI4dhwfbmXc',
    appId: '1:952082308730:android:7a9c4859429592751d25c3',
    messagingSenderId: '952082308730',
    projectId: 'auth-app-savage',
    storageBucket: 'auth-app-savage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5rkRuH293XRhfEDGi8yVVQKSH5aS8EVQ',
    appId: '1:952082308730:ios:473ec471c82aa0d91d25c3',
    messagingSenderId: '952082308730',
    projectId: 'auth-app-savage',
    storageBucket: 'auth-app-savage.appspot.com',
    iosClientId: '952082308730-o6b157ur6bbmdi712e3203e16sub7ptp.apps.googleusercontent.com',
    iosBundleId: 'np.com.asbin.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5rkRuH293XRhfEDGi8yVVQKSH5aS8EVQ',
    appId: '1:952082308730:ios:473ec471c82aa0d91d25c3',
    messagingSenderId: '952082308730',
    projectId: 'auth-app-savage',
    storageBucket: 'auth-app-savage.appspot.com',
    iosClientId: '952082308730-o6b157ur6bbmdi712e3203e16sub7ptp.apps.googleusercontent.com',
    iosBundleId: 'np.com.asbin.authentication',
  );
}
